language: generic
sudo: required
dist: trusty

matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.6.3
      addons:
        apt:
          sources: 
            - hvr-ghc
          packages:
            - cabal-install-1.16
            - ghc-7.6.3
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons:
        apt:
          sources: 
            - hvr-ghc
          packages:
            - cabal-install-1.18
            - ghc-7.8.4
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons:
        apt:
          sources: 
            - hvr-ghc
          packages:
            - cabal-install-1.22
            - ghc-7.10.1
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - cabal-install-1.22
            - ghc-7.10.2
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - cabal-install-1.22
            - ghc-7.10.3
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
    - env: CABALVER=head GHCVER=head
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - cabal-install-head
            - ghc-head
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export WORKDIR="$PWD"
  - cabal --version

install:
  - travis_retry cabal update

script:
  - cabal sdist &&
    export SRC_DIR=$(cabal info . | awk '{print $2 ;exit}') &&
    export SRC_TGZ="$SRC_DIR.tar.gz" &&
    cd dist/ &&
    if [ ! -f "$SRC_TGZ" ]; then
       echo "expected '$SRC_TGZ' not found" && exit 1;
    else
      tar -xf "$SRC_TGZ" &&
      cd "$SRC_DIR";
    fi

  - $WORKDIR/travis/travis_long cabal install --only-dependencies --enable-tests -v &&
    cabal configure --enable-tests -v2 &&
    $WORKDIR/travis/travis_long cabal build &&
    $WORKDIR/travis/travis_long cabal test && 
    cabal check &&
    $WORKDIR/travis/travis_long cabal haddock && 
    cd .. && 
    cabal install "$SRC_TGZ"

